### PR TITLE
Bump to Juno BaseApp

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
Oh shoot, spoke too soon.

**Comment by bilelmoussaoui** [comment]
@jurf Already fixed that build error. FDO doesn't include enchant anymore which is required to build gtkspell:) it's now fixed

**Comment by jurf** [comment]
bot, build

**Comment by jurf** [comment]
Cheers. Hm, this module could use a reformat…

**Comment by bilelmoussaoui** [comment]
The whole things need a reformat :/ it uses a bizarre indentation... Would fix that once the build is working okay to avoid going through the whole diff for nothing

**Comment by jurf** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Ok it builds gtkspell just fine. It requires a new library libmarkdown. Will add that right now

**Comment by bilelmoussaoui** [comment]
@Philip-Scott Any help with the missing library here? I have no idea which version you're using or where did you get the library from :)

**Comment by Philip-Scott** [comment]
@bilelmoussaoui It's actually `libmarkdown-2` from the ubuntu repos.

Here's what `apt-cache policy` returns:
```
libmarkdown2-dev:
  Installed: 2.2.3b8-2
  Candidate: 2.2.3b8-2
  Version table:
 *** 2.2.3b8-2 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by bilelmoussaoui** [comment]
Closed in favour of #5

**Pull request closed without merging**
